#!/bin/bash
# setup-offline.sh — установка IWE-шаблона под Qwen Code (Windows / git bash / offline).
#
# СОХРАНЯЕТ ОРИГИНАЛЬНУЮ АРХИТЕКТУРУ IWE:
#   workspace = ВНЕШНЯЯ папка (например ~/IWE), FMT-репо лежит ВНУТРИ неё
#   (~/IWE/FMT-exocortex-template/). Установка разворачивает файлы из FMT в
#   workspace — ровно как оригинальный setup.sh. FMT остаётся чистым upstream'ом.
#
# Раскладка после установки:
#   ~/IWE/                              ← workspace (IWE_ROOT / IWE_WORKSPACE)
#   ├── FMT-exocortex-template/         ← этот репозиторий (source, обновляемый)
#   ├── QWEN.md                         ← развёрнут из FMT (подставлены пути)
#   ├── .qwen/                          ← развёрнут из FMT (settings, hooks, skills...)
#   ├── .iwe-runtime/                   ← сгенерирован build-runtime.sh
#   ├── .mcp.json, params.yaml          ← развёрнуты из FMT
#   ├── memory/                         ← симлинк на ~/.qwen/projects/<proj>/memory (или копия)
#   └── DS-strategy/                    ← governance-репо из seed/strategy
#
# Отличия от оригинального setup.sh:
#   - offline: без gh/curl/cloud/OAuth/DataPolicy
#   - без планировщика (launchd/cron) — роли запускаются вручную (MANUAL-JOBS.md)
#   - git bash: GNU sed, env-переменные в ~/.bashrc (не ~/.zshenv)
#   - агент Qwen Code (qwen) вместо Claude Code
#   - симлинк memory с fallback на копию (симлинки в git bash на Windows капризны)
#
# Запуск (ИЗ каталога FMT-репо, после распаковки ZIP в ~/IWE/FMT-exocortex-template):
#   bash setup-offline.sh
#   bash setup-offline.sh --yes        # значения по умолчанию, без вопросов
#   bash setup-offline.sh --dry-run    # показать план без изменений
#
set -euo pipefail

TEMPLATE_DIR="$(cd "$(dirname "$0")" && pwd)"
AUTO_YES=false
DRY_RUN=false
for arg in "$@"; do
  case "$arg" in
    --yes)     AUTO_YES=true ;;
    --dry-run) DRY_RUN=true ;;
    --help|-h) sed -n '2,40p' "$0"; exit 0 ;;
  esac
done

# --- GNU sed (git bash) ---
if ! sed --version >/dev/null 2>&1; then
  echo "ОШИБКА: нужен GNU sed (есть в git bash). BSD/macOS sed не поддерживается." >&2
  exit 1
fi
sed_inplace() { sed -i "$@"; }

echo "=== IWE offline setup (Qwen Code / Windows / git bash) ==="
echo

# --- Параметры ---
DEFAULT_WORKSPACE="$(dirname "$TEMPLATE_DIR")"   # родитель FMT-репо = workspace
if $AUTO_YES; then
  WORKSPACE_DIR="$DEFAULT_WORKSPACE"
  GOVERNANCE_REPO="DS-strategy"
  GITHUB_USER="local"
else
  read -rp "Workspace (внешняя папка IWE) [$DEFAULT_WORKSPACE]: " WORKSPACE_DIR
  WORKSPACE_DIR="${WORKSPACE_DIR:-$DEFAULT_WORKSPACE}"
  read -rp "Governance-репо (личный хаб) [DS-strategy]: " GOVERNANCE_REPO
  GOVERNANCE_REPO="${GOVERNANCE_REPO:-DS-strategy}"
  read -rp "GitHub username (offline — можно 'local') [local]: " GITHUB_USER
  GITHUB_USER="${GITHUB_USER:-local}"
fi
WORKSPACE_DIR="${WORKSPACE_DIR/#\~/$HOME}"

HOME_DIR="$HOME"
CLAUDE_PROJECT_SLUG="$(echo "$WORKSPACE_DIR" | tr '/' '-')"
QWEN_PATH="$(command -v qwen 2>/dev/null || echo 'qwen')"
ENV_FILE="$WORKSPACE_DIR/.exocortex.env"
IWE_RUNTIME_PATH="$WORKSPACE_DIR/.iwe-runtime"
QWEN_MEMORY_DIR="$HOME/.qwen/projects/$CLAUDE_PROJECT_SLUG/memory"

echo
echo "  Workspace:        $WORKSPACE_DIR"
echo "  FMT (template):   $TEMPLATE_DIR"
echo "  Home:             $HOME_DIR"
echo "  Governance repo:  $GOVERNANCE_REPO"
echo "  qwen CLI:         $QWEN_PATH"
echo "  Memory dir:       $QWEN_MEMORY_DIR"
echo

if ! $AUTO_YES && ! $DRY_RUN; then
  read -rp "Продолжить установку? (y/n) " ans
  case "$ans" in y|Y) ;; *) echo "Отменено."; exit 0 ;; esac
fi

run() { if $DRY_RUN; then echo "  [dry-run] $*"; else eval "$@"; fi; }

# --- .exocortex.env (минимальный, offline) ---
echo "[0] Запись .exocortex.env..."
if ! $DRY_RUN; then
  mkdir -p "$WORKSPACE_DIR"
  cat > "$ENV_FILE" <<ENVEOF
# IWE offline config (git bash / Qwen Code). Generated by setup-offline.sh.
HOME_DIR=$HOME_DIR
WORKSPACE_DIR=$WORKSPACE_DIR
CLAUDE_PATH=$QWEN_PATH
CLAUDE_PROJECT_SLUG=$CLAUDE_PROJECT_SLUG
TIMEZONE_HOUR=4
TIMEZONE_DESC=offline
GITHUB_USER=$GITHUB_USER
GOVERNANCE_REPO=$GOVERNANCE_REPO
IWE_TEMPLATE=$TEMPLATE_DIR
IWE_RUNTIME=$IWE_RUNTIME_PATH
ENVEOF
  chmod 600 "$ENV_FILE"
  echo "  ✓ $ENV_FILE"
fi

# --- [1] Сгенерировать runtime (.iwe-runtime/) ---
echo "[1] Building generated runtime (.iwe-runtime/)..."
if [ -f "$TEMPLATE_DIR/setup/build-runtime.sh" ]; then
  if $DRY_RUN; then
    bash "$TEMPLATE_DIR/setup/build-runtime.sh" --dry-run --workspace "$WORKSPACE_DIR" --env-file "$ENV_FILE" 2>&1 | sed 's/^/  /' || true
  else
    bash "$TEMPLATE_DIR/setup/build-runtime.sh" --workspace "$WORKSPACE_DIR" --env-file "$ENV_FILE" 2>&1 | sed 's/^/  /' || \
      echo "  ⚠ build-runtime завершился с ошибкой — роли можно собрать позже; основная установка продолжается"
  fi
fi

# --- [2] QWEN.md → workspace (с подстановкой) ---
echo "[2] Installing QWEN.md..."
if ! $DRY_RUN; then
  cp "$TEMPLATE_DIR/QWEN.md" "$WORKSPACE_DIR/QWEN.md"
  sed_inplace \
    -e "s|{{HOME_DIR}}|$HOME_DIR|g" \
    -e "s|{{WORKSPACE_DIR}}|$WORKSPACE_DIR|g" \
    -e "s|{{GOVERNANCE_REPO}}|$GOVERNANCE_REPO|g" \
    -e "s|{{STRATEGY_REPO}}|$GOVERNANCE_REPO|g" \
    -e "s|{{GITHUB_USER}}|$GITHUB_USER|g" \
    -e "s|{{CLAUDE_PROJECT_SLUG}}|$CLAUDE_PROJECT_SLUG|g" \
    -e "s|{{IWE_TEMPLATE}}|$TEMPLATE_DIR|g" \
    -e "s|{{IWE_RUNTIME}}|$IWE_RUNTIME_PATH|g" \
    "$WORKSPACE_DIR/QWEN.md"
  cp "$WORKSPACE_DIR/QWEN.md" "$WORKSPACE_DIR/.qwen.md.base"
  echo "  ✓ $WORKSPACE_DIR/QWEN.md (+ .qwen.md.base)"
fi

# --- [3] memory → ~/.qwen/projects/<proj>/memory + symlink workspace/memory ---
echo "[3] Installing memory..."
if ! $DRY_RUN; then
  mkdir -p "$QWEN_MEMORY_DIR"
  cp "$TEMPLATE_DIR/memory/"*.md "$QWEN_MEMORY_DIR/" 2>/dev/null || true
  for f in "$TEMPLATE_DIR/memory/"*.yaml "$TEMPLATE_DIR/memory/"*.yml; do
    [ -f "$f" ] && cp "$f" "$QWEN_MEMORY_DIR/"
  done
  echo "  ✓ memory → $QWEN_MEMORY_DIR"
  if [ ! -e "$WORKSPACE_DIR/memory" ]; then
    if MSYS=winsymlinks:nativestrict ln -s "$QWEN_MEMORY_DIR" "$WORKSPACE_DIR/memory" 2>/dev/null && [ -L "$WORKSPACE_DIR/memory" ]; then
      echo "  ✓ симлинк: $WORKSPACE_DIR/memory → $QWEN_MEMORY_DIR"
    else
      rm -f "$WORKSPACE_DIR/memory" 2>/dev/null || true
      cp -r "$QWEN_MEMORY_DIR" "$WORKSPACE_DIR/memory"
      echo "  ⚠ симлинки недоступны (Windows) → memory СКОПИРОВАН в $WORKSPACE_DIR/memory"
      echo "    Правки памяти агентом идут в $QWEN_MEMORY_DIR; при расхождении синхронизируй вручную:"
      echo "      cp $QWEN_MEMORY_DIR/*.md $WORKSPACE_DIR/memory/"
    fi
  else
    echo "  ○ $WORKSPACE_DIR/memory уже существует — пропуск"
  fi
fi

# --- [4] .qwen/ → workspace (settings, hooks, skills, rules, lib, config, detectors, scripts, agents) ---
echo "[4] Installing .qwen/ → workspace..."
if ! $DRY_RUN; then
  mkdir -p "$WORKSPACE_DIR/.qwen"
  for subdir in skills hooks rules lib config detectors scripts agents; do
    if [ -d "$TEMPLATE_DIR/.qwen/$subdir" ]; then
      cp -r "$TEMPLATE_DIR/.qwen/$subdir" "$WORKSPACE_DIR/.qwen/"
      echo "  ✓ .qwen/$subdir/"
    fi
  done
  [ -f "$TEMPLATE_DIR/.qwen/settings.json" ] && cp "$TEMPLATE_DIR/.qwen/settings.json" "$WORKSPACE_DIR/.qwen/settings.json" && echo "  ✓ .qwen/settings.json"
  [ -f "$TEMPLATE_DIR/.qwen/settings.local.json" ] && cp "$TEMPLATE_DIR/.qwen/settings.local.json" "$WORKSPACE_DIR/.qwen/settings.local.json" && echo "  ✓ .qwen/settings.local.json"
fi

# --- [4c] .mcp.json → workspace ---
echo "[4c] Installing .mcp.json (offline — пустой)..."
if ! $DRY_RUN; then
  [ -f "$TEMPLATE_DIR/.mcp.json" ] && cp "$TEMPLATE_DIR/.mcp.json" "$WORKSPACE_DIR/.mcp.json" && echo "  ✓ .mcp.json"
fi

# --- [4d] IWE env-переменные (~/.bashrc) ---
echo "[4d] Installing IWE environment variables..."
if [ -f "$TEMPLATE_DIR/setup/install-iwe-paths.sh" ]; then
  if $DRY_RUN; then
    bash "$TEMPLATE_DIR/setup/install-iwe-paths.sh" --workspace "$WORKSPACE_DIR" --governance "$GOVERNANCE_REPO" --template "$TEMPLATE_DIR" --dry-run 2>&1 | sed 's/^/  /' || true
  else
    bash "$TEMPLATE_DIR/setup/install-iwe-paths.sh" --workspace "$WORKSPACE_DIR" --governance "$GOVERNANCE_REPO" --template "$TEMPLATE_DIR" 2>&1 | sed 's/^/  /' || true
    echo "  ℹ  Перезапусти git bash или: source ~/.bashrc"
  fi
fi

# --- [5] Роли: планировщик недоступен ---
echo "[5] Роли (автоматизация)... пропущено (нет планировщика)."
echo "  Роли запускаются ВРУЧНУЮ — см. $TEMPLATE_DIR/MANUAL-JOBS.md"

# --- [6] DS-strategy из seed/strategy (локальный git, без gh) ---
echo "[6] Setting up $GOVERNANCE_REPO..."
MY_STRATEGY_DIR="$WORKSPACE_DIR/$GOVERNANCE_REPO"
STRATEGY_TEMPLATE="$TEMPLATE_DIR/seed/strategy"
if [ -d "$MY_STRATEGY_DIR/.git" ]; then
  echo "  ○ $GOVERNANCE_REPO уже существует (git) — пропуск"
elif $DRY_RUN; then
  echo "  [dry-run] создал бы $MY_STRATEGY_DIR из seed/strategy + git init (локально)"
elif [ -d "$STRATEGY_TEMPLATE" ]; then
  cp -r "$STRATEGY_TEMPLATE" "$MY_STRATEGY_DIR"
  ( cd "$MY_STRATEGY_DIR" && git init -q && git add -A && git -c user.email=local@iwe -c user.name=IWE commit -qm "Initial exocortex: $GOVERNANCE_REPO governance hub" )
  echo "  ✓ $MY_STRATEGY_DIR (локальный git, без remote)"
else
  echo "  ⚠ seed/strategy не найден — пропуск"
fi

# --- [7] Base repos (FPF, SPF): offline — вручную ---
echo "[7] Base repos (FPF, SPF)... пропущено (offline)."
echo "  Если нужны — перенеси FPF/ и SPF/ в $WORKSPACE_DIR/ вручную (ZIP)."

echo
echo "=== Готово ==="
echo "Дальше:"
echo "  1. source ~/.bashrc"
echo "  2. cd \"$WORKSPACE_DIR\"     # workspace, НЕ каталог FMT"
echo "  3. qwen                       # запустить агента из workspace"
echo
echo "Перенос своих знаний (архив РП, паки, память) — см. $TEMPLATE_DIR/MIGRATION.md"
